version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download dependencies
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Build application
          command: go build -o myapp
      - run:
          name: Check for vulnerabilities
          command: |
            go install golang.org/x/vuln/cmd/govulncheck@latest
            govulncheck ./...
      - persist_to_workspace:
          root: .
          paths:
            - myapp
      - store_artifacts:
          path: myapp

  test:
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download dependencies
          command: go mod download
      - run:
          name: Run tests
          command: go test -coverprofile=coverage.out -parallel 4
      - store_test_results:
          path: coverage.out

  deploy_staging:
    docker:
      - image: cimg/go:1.23
      
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:R+RxsogfKi8zGNT3BbfmdbqDvkCOXKYIq+FTwjPlfHE"
      - attach_workspace:
          at: .
      - run:
          name: List workspace contents
          command: ls -l .
      - run:
          name: Deploy to staging server
          command: |
            ###sudo mkdir -p /var/www/myapp
            ###sudo cp ./myapp /var/www/myapp/
            sudo ssh -o StrictHostKeyChecking=no foo@ec2-54-248-203-71.ap-northeast-1.compute.amazonaws.com
            ###scp -o StrictHostKeyChecking=no ./myapp ${SSH_USER}@${SERVER_NAME}:/home/ubuntu/myapp
  
      - run:
          name: List myapp
          command: sudo ls -l /var/www/myapp/

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_staging:
          requires:
            - test
          ###filters:
            ###branches:
              ###only:
                ###- main
