version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - restore_cache: # キャッシュの復元
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - go mod download
      - save_cache: # キャッシュの保存
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - go build -o myapp
      - go test ./... -coverprofile=coverage.out
      - store_artifacts:
          path: myapp
      - store_test_results:
          path: coverage.out
